name: MaxHost Build

on:
  push:
    branches: [ emt ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # Using Ubuntu is faster for Docker
    container: paisseon/theos-action:latest # Pre-baked with Theos and SDKs

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Tweak
        run: |
          # We are already in the Theos environment
          export TARGET=iphone:clang:latest:14.0
          # If your Makefile is inside a subfolder, we cd into it
          cd SatellaJailed/Tweak && make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MaxHost-Satella
          path: SatellaJailed/Tweak/packages/*.deb
