name: MaxHost Build

on:
  push:
    branches: [ emt ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        uses: Randomblock1/theos-action@v1
        with:
          theos-sdks: 'https://github.com/theos/sdks'
          orion: true 

      - name: Build Tweak
        run: |
          export TARGET=iphone:clang:latest:14.0
          # We must enter the Tweak folder where the Makefile lives
          cd Tweak && make package FINALPACKAGE=1
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MaxHost-Satella
          path: Tweak/packages/*.deb
